import type { Campaign, User, Investment, Transaction, Notification, BlogPost } from './types'

export const campaigns: Campaign[] = [
  {
    id: 'c001',
    titre: 'Tomates cerises bio - Campagne printemps 2024',
    slug: 'tomates-cerises-bio-2024',
    description: 'La Coopérative Agri-Bouaké lance sa 4ème campagne de production de tomates cerises biologiques certifiées. Nos terres argilo-limoneuses du centre de la Côte d\'Ivoire offrent des conditions idéales pour une production de qualité premium. Nous travaillons avec un agronome senior certifié et avons un contrat d\'achat ferme avec SOCOCÉ pour l\'ensemble de la récolte.',
    descriptionCourte: 'Production de tomates cerises bio avec contrat d\'achat garanti par SOCOCÉ. Irrigation goutte-à-goutte installée.',
    produit: 'Tomates',
    variete: 'Tomates cerises bio',
    region: 'Bouaké',
    ville: 'Bouaké',
    cooperativeId: 'coop001',
    cooperativeNom: 'Coopérative Agri-Bouaké',
    cooperativeMembers: 45,
    surface: 12,
    rendementAttendu: 180,
    montantCible: 8500000,
    montantLeve: 6120000,
    nombreInvestisseurs: 127,
    roiMin: 18,
    roiMax: 22,
    dureeJours: 90,
    dateDebut: '2024-03-01',
    dateFin: '2025-05-30',
    dateRecolte: '2025-07-15',
    status: 'levee',
    risque: 'faible',
    image: 'https://images.unsplash.com/photo-1592997571659-0b21ff64313b?w=800',
    images: ['https://images.unsplash.com/photo-1592997571659-0b21ff64313b?w=800'],
    acheteur: 'SOCOCÉ',
    prixGarantiKg: 950,
    quantiteContratTonnes: 160,
    agronome: 'Dr. Kouassi Emmanuel',
    scoreAgronomique: 92,
    assurance: true,
    tags: ['bio', 'certifié', 'irrigation'],
    createdAt: '2024-02-15',
  },
  {
    id: 'c002',
    titre: 'Maïs hybride - Vallée du N\'Zi 2024',
    slug: 'mais-hybride-nzi-2024',
    description: 'La Coopérative des Producteurs de la Vallée du N\'Zi présente sa campagne de production de maïs hybride haute rendement. Les terres alluvionnaires de la vallée bénéficient d\'une fertilité naturelle exceptionnelle. Contrat d\'achat ferme avec Nestlé CI.',
    descriptionCourte: 'Maïs hybride haute rendement dans la vallée du N\'Zi avec contrat Nestlé CI.',
    produit: 'Maïs',
    variete: 'Maïs hybride SEEDCO',
    region: 'Divo',
    ville: 'Divo',
    cooperativeId: 'coop002',
    cooperativeNom: 'Coop. Vallée du N\'Zi',
    cooperativeMembers: 67,
    surface: 35,
    rendementAttendu: 2450,
    montantCible: 15000000,
    montantLeve: 15000000,
    nombreInvestisseurs: 234,
    roiMin: 20,
    roiMax: 25,
    dureeJours: 110,
    dateDebut: '2024-01-15',
    dateFin: '2025-04-30',
    dateRecolte: '2025-06-20',
    status: 'production',
    risque: 'faible',
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800'],
    acheteur: 'Nestlé CI',
    prixGarantiKg: 185,
    quantiteContratTonnes: 2200,
    agronome: 'M. Bamba Seydou',
    scoreAgronomique: 88,
    assurance: true,
    tags: ['hybride', 'haute-rendement'],
    createdAt: '2024-01-01',
  },
  {
    id: 'c003',
    titre: 'Sésame blanc export - Région de Korhogo',
    slug: 'sesame-blanc-korhogo-2024',
    description: 'La Coopérative Sésame du Nord lance sa campagne annuelle de production de sésame blanc destiné à l\'export vers l\'Asie. La région de Korhogo bénéficie d\'un climat semi-aride idéal. Nos producteurs appliquent les normes GlobalGAP pour les marchés japonais et coréens.',
    descriptionCourte: 'Sésame blanc certifié GlobalGAP pour export vers le marché japonais et coréen.',
    produit: 'Sésame',
    variete: 'Sésame blanc HF',
    region: 'Korhogo',
    ville: 'Korhogo',
    cooperativeId: 'coop003',
    cooperativeNom: 'Coop. Sésame du Nord',
    cooperativeMembers: 89,
    surface: 80,
    rendementAttendu: 480,
    montantCible: 12000000,
    montantLeve: 4200000,
    nombreInvestisseurs: 89,
    roiMin: 22,
    roiMax: 28,
    dureeJours: 120,
    dateDebut: '2024-04-01',
    dateFin: '2025-06-30',
    dateRecolte: '2025-09-15',
    status: 'levee',
    risque: 'modere',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800'],
    acheteur: 'CARGILL Export',
    prixGarantiKg: 1200,
    quantiteContratTonnes: 400,
    agronome: 'M. Coulibaly Ibrahim',
    scoreAgronomique: 85,
    assurance: true,
    tags: ['export', 'GlobalGAP', 'Asie'],
    createdAt: '2024-03-15',
  },
  {
    id: 'c004',
    titre: 'Anacarde premium - Côte Ouest 2024',
    slug: 'anacarde-cote-ouest-2024',
    description: 'Rejoignez la Coopérative Anacarde Ouest pour notre campagne de production d\'anacarde de qualité premium. La Côte d\'Ivoire est le 1er exportateur mondial d\'anacarde brut. Notre coopérative produit des noix W210 et W240 destinées aux transformateurs locaux et à l\'export.',
    descriptionCourte: 'Noix de cajou W210/W240 premium pour transformateurs locaux et export international.',
    produit: 'Anacarde',
    variete: 'Anacarde W210/W240',
    region: 'San-Pédro',
    ville: 'San-Pédro',
    cooperativeId: 'coop004',
    cooperativeNom: 'Coop. Anacarde Ouest',
    cooperativeMembers: 123,
    surface: 200,
    rendementAttendu: 600,
    montantCible: 25000000,
    montantLeve: 18750000,
    nombreInvestisseurs: 312,
    roiMin: 15,
    roiMax: 20,
    dureeJours: 180,
    dateDebut: '2024-02-01',
    dateFin: '2025-04-30',
    dateRecolte: '2025-07-30',
    status: 'production',
    risque: 'faible',
    image: 'https://images.unsplash.com/photo-1602575668981-a5a68b37a83b?w=800',
    images: ['https://images.unsplash.com/photo-1602575668981-a5a68b37a83b?w=800'],
    acheteur: 'OLAM CI',
    prixGarantiKg: 450,
    quantiteContratTonnes: 550,
    agronome: 'Mme. Touré Aïssatou',
    scoreAgronomique: 94,
    assurance: true,
    tags: ['premium', 'export', 'W210'],
    createdAt: '2024-01-20',
  },
  {
    id: 'c005',
    titre: 'Cacao fin de goût - Région d\'Abengourou',
    slug: 'cacao-abengourou-2024',
    description: 'Investissez dans la production de cacao fin de goût certifié Rainforest Alliance. Abengourou est reconnu pour la qualité aromatique exceptionnelle de ses fèves. Notre programme de fermentation contrôlée garantit un profil aromatique premium apprécié par les chocolatiers européens.',
    descriptionCourte: 'Cacao certifié Rainforest Alliance avec fermentation contrôlée pour chocolatiers européens.',
    produit: 'Cacao',
    variete: 'Cacao Forestaro',
    region: 'Abengourou',
    ville: 'Abengourou',
    cooperativeId: 'coop005',
    cooperativeNom: 'Coop. Cacao Centre-Est',
    cooperativeMembers: 156,
    surface: 150,
    rendementAttendu: 375,
    montantCible: 20000000,
    montantLeve: 1500000,
    nombreInvestisseurs: 28,
    roiMin: 18,
    roiMax: 23,
    dureeJours: 150,
    dateDebut: '2025-05-01',
    dateFin: '2025-08-31',
    dateRecolte: '2025-11-30',
    status: 'levee',
    risque: 'modere',
    image: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800',
    images: ['https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800'],
    acheteur: 'Barry Callebaut',
    prixGarantiKg: 3200,
    quantiteContratTonnes: 300,
    agronome: 'Dr. N\'Dri Jean-Paul',
    scoreAgronomique: 96,
    assurance: true,
    tags: ['Rainforest Alliance', 'premium', 'Europe'],
    createdAt: '2024-04-15',
  },
  {
    id: 'c006',
    titre: 'Riz paddy - Plaines de la Comoé',
    slug: 'riz-paddy-comoe-2024',
    description: 'La Coopérative Rizicole de la Comoé développe la production rizicole irriguée dans les plaines alluviales de la Comoé. Dans le cadre du Programme National de Développement Rizicole, notre coopérative bénéficie d\'un accompagnement technique de l\'ANADER.',
    descriptionCourte: 'Riz paddy irrigué avec accompagnement ANADER dans le programme national rizicole.',
    produit: 'Riz',
    variete: 'Riz IR841',
    region: 'Abengourou',
    ville: 'Aboisso',
    cooperativeId: 'coop006',
    cooperativeNom: 'Coop. Rizicole Comoé',
    cooperativeMembers: 78,
    surface: 60,
    rendementAttendu: 2400,
    montantCible: 9000000,
    montantLeve: 9000000,
    nombreInvestisseurs: 145,
    roiMin: 16,
    roiMax: 19,
    dureeJours: 100,
    dateDebut: '2023-12-01',
    dateFin: '2024-02-29',
    dateRecolte: '2024-04-30',
    status: 'terminee',
    risque: 'faible',
    image: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=800',
    images: ['https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=800'],
    acheteur: 'Société OLICO',
    prixGarantiKg: 220,
    quantiteContratTonnes: 2200,
    agronome: 'M. Kassi Théodore',
    scoreAgronomique: 91,
    assurance: false,
    tags: ['irrigué', 'ANADER'],
    createdAt: '2023-11-15',
  },
  {
    id: 'c007',
    titre: 'Soja certifié - Nord Côte d\'Ivoire',
    slug: 'soja-nord-ci-2024',
    description: 'La Coopérative Soja du Nord produit du soja certifié non-OGM destiné aux huileries industrielles de la sous-région. Avec la montée en puissance de l\'industrie agroalimentaire en Afrique de l\'Ouest, la demande en soja local est en forte croissance.',
    descriptionCourte: 'Soja certifié non-OGM pour huileries industrielles ouest-africaines. Demande croissante.',
    produit: 'Soja',
    variete: 'Soja TGx 1835-10E',
    region: 'Korhogo',
    ville: 'Ferkessédougou',
    cooperativeId: 'coop008',
    cooperativeNom: 'Coop. Soja du Nord',
    cooperativeMembers: 56,
    surface: 45,
    rendementAttendu: 1350,
    montantCible: 11000000,
    montantLeve: 7700000,
    nombreInvestisseurs: 156,
    roiMin: 17,
    roiMax: 21,
    dureeJours: 95,
    dateDebut: '2024-03-15',
    dateFin: '2025-06-15',
    dateRecolte: '2025-08-30',
    status: 'levee',
    risque: 'faible',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800',
    images: ['https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800'],
    acheteur: 'COSMIVOIRE',
    prixGarantiKg: 350,
    quantiteContratTonnes: 1200,
    agronome: 'Mme. Diallo Fatoumata',
    scoreAgronomique: 89,
    assurance: true,
    tags: ['non-OGM', 'certifié'],
    createdAt: '2024-03-01',
  },
]

export const currentUser: User = {
  id: 'u001',
  nom: 'Kouamé',
  prenom: 'Jean-Baptiste',
  email: 'jb.kouame@gmail.com',
  telephone: '+225 07 12 34 56 78',
  role: 'investisseur',
  kycStatus: 'verifie',
  ville: 'Abidjan',
  pays: 'Côte d\'Ivoire',
  dateInscription: '2023-06-15',
  soldeWallet: 2450000,
  totalInvesti: 12500000,
  totalROI: 2625000,
  isActive: true,
}

export const investments: Investment[] = [
  {
    id: 'inv001',
    userId: 'u001',
    campaignId: 'c001',
    campaignTitre: 'Tomates cerises bio - Campagne printemps 2024',
    campaignProduit: 'Tomates',
    montant: 500000,
    roiExpected: 20,
    dateInvestissement: '2024-03-05',
    dateRetourPrev: '2025-07-15',
    status: 'actif',
  },
  {
    id: 'inv002',
    userId: 'u001',
    campaignId: 'c002',
    campaignTitre: 'Maïs hybride - Vallée du N\'Zi 2024',
    campaignProduit: 'Maïs',
    montant: 1000000,
    roiExpected: 22,
    dateInvestissement: '2024-01-20',
    dateRetourPrev: '2025-06-20',
    status: 'actif',
  },
  {
    id: 'inv003',
    userId: 'u001',
    campaignId: 'c006',
    campaignTitre: 'Riz paddy - Plaines de la Comoé',
    campaignProduit: 'Riz',
    montant: 750000,
    roiExpected: 17,
    roiActual: 17.5,
    dateInvestissement: '2023-12-10',
    dateRetourPrev: '2024-04-30',
    status: 'termine',
  },
  {
    id: 'inv004',
    userId: 'u001',
    campaignId: 'c004',
    campaignTitre: 'Anacarde premium - Côte Ouest 2024',
    campaignProduit: 'Anacarde',
    montant: 2000000,
    roiExpected: 18,
    dateInvestissement: '2024-02-15',
    dateRetourPrev: '2025-07-30',
    status: 'actif',
  },
]

export const transactions: Transaction[] = [
  {
    id: 'txn001',
    userId: 'u001',
    type: 'depot',
    montant: 1000000,
    status: 'valide',
    description: 'Dépôt Orange Money',
    reference: 'DEP-2024-001234',
    methodePaiement: 'orange_money',
    date: '2024-03-01',
  },
  {
    id: 'txn002',
    userId: 'u001',
    type: 'investissement',
    montant: 500000,
    status: 'valide',
    description: 'Investissement - Tomates cerises bio',
    reference: 'INV-2024-000456',
    campaignId: 'c001',
    date: '2024-03-05',
  },
  {
    id: 'txn003',
    userId: 'u001',
    type: 'roi',
    montant: 131250,
    status: 'valide',
    description: 'ROI - Riz paddy Comoé (17.5%)',
    reference: 'ROI-2024-000789',
    campaignId: 'c006',
    date: '2024-05-02',
  },
  {
    id: 'txn004',
    userId: 'u001',
    type: 'depot',
    montant: 2000000,
    status: 'valide',
    description: 'Dépôt Wave',
    reference: 'DEP-2024-005678',
    methodePaiement: 'wave',
    date: '2024-02-10',
  },
  {
    id: 'txn005',
    userId: 'u001',
    type: 'investissement',
    montant: 1000000,
    status: 'valide',
    description: 'Investissement - Maïs hybride N\'Zi',
    reference: 'INV-2024-000891',
    campaignId: 'c002',
    date: '2024-01-20',
  },
  {
    id: 'txn006',
    userId: 'u001',
    type: 'retrait',
    montant: 500000,
    status: 'valide',
    description: 'Retrait Orange Money',
    reference: 'WIT-2024-000123',
    methodePaiement: 'orange_money',
    date: '2024-04-15',
  },
]

export const notifications: Notification[] = [
  {
    id: 'n001',
    userId: 'u001',
    type: 'roi',
    titre: 'ROI distribué 🎉',
    message: 'Votre ROI de 131 250 FCFA pour la campagne Riz paddy Comoé a été versé sur votre wallet.',
    lu: false,
    date: '2024-05-02',
    link: '/dashboard/wallet',
  },
  {
    id: 'n002',
    userId: 'u001',
    type: 'campagne',
    titre: 'Campagne en production',
    message: 'La campagne Maïs hybride - Vallée du N\'Zi est maintenant en phase de production.',
    lu: false,
    date: '2024-05-01',
    link: '/campagnes/mais-hybride-nzi-2024',
  },
  {
    id: 'n003',
    userId: 'u001',
    type: 'rapport',
    titre: 'Nouveau rapport agronomique',
    message: 'Un rapport agronomique a été publié pour la campagne Tomates cerises bio.',
    lu: true,
    date: '2024-04-28',
    link: '/campagnes/tomates-cerises-bio-2024',
  },
  {
    id: 'n004',
    userId: 'u001',
    type: 'kyc',
    titre: 'KYC vérifié ✅',
    message: 'Votre identité a été vérifiée avec succès. Vous avez accès à toutes les fonctionnalités.',
    lu: true,
    date: '2024-03-20',
    link: '/dashboard/kyc',
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: 'b001',
    slug: 'investir-agriculture-cote-ivoire-guide-complet',
    titre: 'Guide complet pour investir dans l\'agriculture ivoirienne',
    extrait: 'Découvrez comment l\'agriculture ivoirienne offre des opportunités d\'investissement à fort rendement tout en contribuant au développement économique local.',
    contenu: 'L\'agriculture représente environ 20% du PIB de la Côte d\'Ivoire et emploie plus de 50% de la population active. Investir dans ce secteur via A-FUND offre des rendements attractifs de 15 à 25% tout en ayant un impact direct sur les communautés rurales. La clé du succès réside dans la sélection rigoureuse des projets, la certification agronomique et les contrats d\'achat garantis qui sécurisent le capital des investisseurs.',
    auteur: 'Joël YEMIAN',
    categorie: 'Conseils investissement',
    image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
    datePublication: '2024-04-20',
    tempsLecture: 8,
    tags: ['investissement', 'agriculture', 'guide'],
  },
  {
    id: 'b002',
    slug: 'cooperative-agri-bouake-succes-tomates',
    titre: 'Success story : La Coopérative Agri-Bouaké triple sa production',
    extrait: 'Comment la Coopérative Agri-Bouaké a transformé ses pratiques agricoles grâce au financement participatif et atteint un ROI de 22% pour ses investisseurs.',
    contenu: 'En 2022, la Coopérative Agri-Bouaké avait du mal à financer ses intrants agricoles. Depuis son partenariat avec A-FUND, tout a changé. Avec trois campagnes réussies et un ROI moyen de 21%, la coopérative a pu investir dans un système d\'irrigation goutte-à-goutte et former ses membres aux bonnes pratiques agricoles. Résultat : une production triplée et des revenus en hausse pour les 45 membres.',
    auteur: 'Équipe A-FUND',
    categorie: 'Success stories',
    image: 'https://images.unsplash.com/photo-1592997571659-0b21ff64313b?w=800',
    datePublication: '2024-04-10',
    tempsLecture: 5,
    tags: ['success story', 'coopérative', 'tomates'],
  },
  {
    id: 'b003',
    slug: 'anacarde-cote-ivoire-premier-exportateur',
    titre: 'L\'anacarde ivoirien : 1er exportateur mondial, opportunités record',
    extrait: 'La Côte d\'Ivoire produit 45% de l\'anacarde mondial. Voici pourquoi investir dans cette filière est une décision stratégique en 2024.',
    contenu: 'Avec 900 000 tonnes produites en 2023, la Côte d\'Ivoire confirme sa position de leader mondial de l\'anacarde. La demande asiatique continue de croître de 8% par an. Les coopératives qui travaillent avec A-FUND dans cette filière affichent des ROI entre 15 et 20%, soutenus par des contrats d\'achat fermes avec des négociants internationaux comme OLAM et CARGILL.',
    auteur: 'Dr. Kouadio Sylvain',
    categorie: 'Agriculture',
    image: 'https://images.unsplash.com/photo-1602575668981-a5a68b37a83b?w=800',
    datePublication: '2024-03-28',
    tempsLecture: 6,
    tags: ['anacarde', 'export', 'investissement'],
  },
  {
    id: 'b004',
    slug: 'securite-investissement-agricole',
    titre: 'Comment A-FUND sécurise vos investissements agricoles',
    extrait: 'Contrats d\'achat, assurances, certifications agronomiques : découvrez notre mécanisme de protection à 3 niveaux.',
    contenu: 'La sécurité des investissements est notre priorité absolue. Notre système de protection repose sur trois piliers : la validation agronomique indépendante (score minimum 80/100), le contrat d\'achat pré-signé avec un acheteur vérifié, et l\'assurance récolte pour les campagnes éligibles. Ce triptyque nous permet d\'afficher un taux de succès de 97.4% depuis notre lancement.',
    auteur: 'Joël YEMIAN',
    categorie: 'Général',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800',
    datePublication: '2024-03-15',
    tempsLecture: 7,
    tags: ['sécurité', 'assurance', 'protection'],
  },
]

export const portfolioChartData = [
  { mois: 'Mai 23', valeur: 500000 },
  { mois: 'Juin 23', valeur: 750000 },
  { mois: 'Juil 23', valeur: 750000 },
  { mois: 'Août 23', valeur: 1200000 },
  { mois: 'Sep 23', valeur: 1350000 },
  { mois: 'Oct 23', valeur: 2000000 },
  { mois: 'Nov 23', valeur: 2150000 },
  { mois: 'Déc 23', valeur: 2800000 },
  { mois: 'Jan 24', valeur: 3800000 },
  { mois: 'Fév 24', valeur: 3950000 },
  { mois: 'Mar 24', valeur: 5800000 },
  { mois: 'Avr 24', valeur: 6200000 },
]